version: '3'
services:
  next-example-dev:
    build:
      context: .
      dockerfile: .docker/dev.dockerfile
    image: registry.gitlab.com/rendiriz/next-example:dev
    container_name: 'next-example-dev'
    ports:
      - '15011:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always