cache:
  key: "$CI_BUILD_REF_NAME node:12-alpine"
  paths:
    - node_modules/

stages:
  - build
  - release-dev
  - deploy-dev

build:
  stage: build
  tags:
    - gitlab-runner-gcp-vm-rendi
  image: rastasheep/alpine-node-chromium:8-alpine
  only:
    - "dev"
    - "main"
  variables:
    NODE_ENV: "development"
  script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*

release-dev:
  stage: release-dev
  tags:
    - gitlab-runner-gcp-vm-rendi
  image: docker:latest
  only:
    - "dev"
  environment:
    name: development
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - "docker version"
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -f .docker/dev.dockerfile -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:dev --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:dev"
  after_script:
    - "docker logout ${CI_REGISTRY}"

deploy-dev:
  stage: deploy-dev
  tags:
    - gitlab-runner-gcp-vm-rendi
  image: alpine:latest
  only:
    - "dev"
  environment:
    name: development
  services:
    - docker:dind
  before_script:
    - "which ssh-agent || ( apk update && apk add openssh-client git )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "mkdir -p /home/rendirizkir/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}"
    - scp -o StrictHostKeyChecking=no ./docker-compose-dev.yml ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:/home/rendirizkir/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker-compose -f /home/rendirizkir/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose-dev.yml stop"
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker-compose -f /home/rendirizkir/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose-dev.yml rm next-example-dev"
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:dev"
    - ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker-compose -f /home/rendirizkir/docker-script/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/docker-compose-dev.yml up -d"
